# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # configure proxy settings in vm
   if Vagrant.has_plugin?("vagrant-proxyconf")
  		config.proxy.http     = "<your-proxy-goes-here>"
  		config.proxy.https    = "<your-proxy-goes-here>"
  		config.proxy.no_proxy = "localhost,127.0.0.1"
  	end
  
  config.vm.box = "ubuntu/trusty64"
  config.vm.box_check_update = false

  config.vm.network "forwarded_port", guest: 5432, host: 5432, host_ip: "127.0.0.1"
  config.vm.network "forwarded_port", guest: 5672, host: 5672, host_ip: "127.0.0.1"
  config.vm.network "forwarded_port", guest: 15672, host: 15672, host_ip: "127.0.0.1"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
    config.vm.network "private_network", ip: "192.168.33.10"

  config.vm.provider "virtualbox" do |vb|
	vb.cpus = 2
    vb.memory = "4096"
  end


  config.vm.provision "docker", images: ["postgres", "dpage/pgadmin4", "swaggerapi/swagger-editor", "rabbitmq:3-management"] do |d| 	
	d.run "db", 
		image: "postgres", 
		args: "-p 5432:5432 -e POSTGRES_USER=admin -e POSTGRES_PASSWORD=admin"
	d.run "dbclient",
		image: "dpage/pgadmin4:2.1",
		args: "-p 80:80 --link db:db  -e PGADMIN_DEFAULT_EMAIL=admin -e PGADMIN_DEFAULT_PASSWORD=admin"
	d.run "swagger",
		image: "swaggerapi/swagger-editor",
		args: "-p 8080:8080"
	d.run "rabbitmq",
		image: "rabbitmq:3-management",
		args: "--hostname vrabbit -p 15672:15672 -p 5672:5672 -e RABBITMQ_DEFAULT_USER=admin -e RABBITMQ_DEFAULT_PASS=admin"
  end
  
  config.vm.provision "shell", inline: "sudo gpasswd -a vagrant docker"
end
